---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellowhale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hellowhaleapp
  template:
    metadata:
      name: hellowhalepod
      labels:
        app: hellowhaleapp
    spec:
      containers:
      - name: hello-whale-container
        image: vamsijakkula/hello-blue-whale:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service 
metadata:
  name: hello-whale-svc
  labels:
    app: hellowhaleapp
spec:
  selector:
    app: hellowhaleapp
  type: NodePort
  ports:
  - nodePort: 31113
    port: 80
    targetPort: 80
